- id: ruff-conda
  name: ruff-conda
  description: 'Run `ruff` for extremely fast Python linting'
  entry: ruff check --fix --exit-non-zero-on-fix --force-exclude
  language: conda
  types_or: [python, pyi]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"

- id: ruff-format-conda
  name: ruff-format-conda
  description: 'Run `ruff format` for extremely fast Python formatting'
  entry: ruff format --force-exclude
  language: conda
  types_or: [python, pyi]
  args: []
  require_serial: true
  additional_dependencies: []
  minimum_pre_commit_version: "2.9.2"
