- id: ruff-conda
  name: ruff-conda
  description: "Run 'ruff' for extremely fast Python linting"
  entry: ruff --fix --exit-non-zero-on-fix
  language: conda
  require_serial: false
  types: [python]
